export const data = [
  {
    title: "shirt",
    subtitle: "",
    size: "Small",
    color: "red",
    image: "",
    sex: "mens",
    price: 35,
  },
  {
    title: "shirt",
    subtitle: "",
    size: "Small",
    color: "red",
    image: "",
    sex: "mens",
    price: 35,
  },
  {
    title: "shirt",
    subtitle: "",
    size: "Small",
    color: "red",
    image: "",
    sex: "mens",
    price: 35,
  },
  {
    title: "shirt",
    subtitle: "",
    size: "Small",
    color: "red",
    image: "",
    sex: "mens",
    price: 35,
  },
  {
    title: "shirt",
    subtitle: "",
    size: "Small",
    color: "red",
    image: "",
    sex: "mens",
    price: 35,
  },
  {
    title: "shirt",
    subtitle: "",
    size: "Small",
    color: "red",
    image: "",
    sex: "mens",
    price: 35,
  },
  {
    title: "shirt",
    subtitle: "",
    size: "Small",
    color: "red",
    image: "",
    sex: "mens",
    price: 35,
  },
  {
    title: "shirt",
    subtitle: "",
    size: "Small",
    color: "red",
    image: "",
    sex: "mens",
    price: 35,
  },
  {
    title: "shirt",
    subtitle: "",
    size: "Small",
    color: "red",
    image: "",
    sex: "mens",
    price: 35,
  },
  {
    title: "shirt",
    subtitle: "",
    size: "Small",
    color: "red",
    image: "",
    sex: "mens",
    price: 35,
  },
  {
    title: "shirt",
    subtitle: "",
    size: "Small",
    color: "red",
    image: "",
    sex: "mens",
    price: 35,
  },
  {
    title: "shirt",
    subtitle: "",
    size: "Small",
    color: "red",
    image: "",
    sex: "mens",
    price: 35,
  },
  {
    title: "shirt",
    subtitle: "",
    size: "Small",
    color: "red",
    image: "",
    sex: "mens",
    price: 35,
  },
  {
    title: "shirt",
    subtitle: "",
    size: "Small",
    color: "red",
    image: "",
    sex: "mens",
    price: 35,
  },
  {
    title: "shirt",
    subtitle: "",
    size: "Small",
    color: "red",
    image: "",
    sex: "mens",
    price: 35,
  },
  {
    title: "shirt",
    subtitle: "",
    size: "Small",
    color: "red",
    image: "",
    sex: "mens",
    price: 35,
  },
];
